apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nextjs-build-pipeline
  namespace: jegor-nl
spec:
  tasks:
    - name: pull-code
      params:
        - name: repo-url
          type: string
          default: "https://github.com/jopdorp/jegor.nl.git"
        - name: branch
          type: string
          default: "main"
      taskSpec:
        steps:
          - name: clone-repo
            image: alpine/git
            script: |
              git clone $(params.repo-url) -b $(params.branch) /workspace/source
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token
      workspaces:
        - name: source-workspace
      volumes:
        - name: github-token
          secret:
            secretName: github-secret
    
    - name: build-docker-image
      workspaces:
        - name: source-workspace
      params:
        - name: imageTag
          type: string
          description: Tag for the Docker image
          default: "latest"
      taskSpec:
        steps:
          - name: build
            image: docker:27.1
            script: |
              cd /workspace/source
              docker build . -t jegornl:$(params.imageTag)
              docker tag jegornl:$(params.imageTag) harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)
              docker push harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)

    - name: create-github-tag
      params:
        - name: imageTag
          type: string
        - name: repo-url
          type: string
          default: "https://api.github.com/repos/jopdorp/jegor.nl"
      taskSpec:
        steps:
          - name: create-tag
            image: curlimages/curl:7.78.0
            script: |
              curl -H "Authorization: token $(cat /root/.git-credentials)" \
                   -H "Content-Type: application/json" \
                   -X POST $(params.repo-url)/git/refs \
                   -d '{"ref": "refs/tags/$(params.imageTag)", "sha": "$(git rev-parse HEAD)"}'
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token
      volumes:
        - name: github-token
          secret:
            secretName: github-secret

workspaces:
  - name: source-workspace
