apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nextjs-build-pipeline
  namespace: jegor-nl
spec:
  tasks:
    - name: build-docker-image
      taskSpec:
        steps:
          - name: build
            image: docker:27.1
            script: |
              #!/bin/sh
              docker build . -t jegornl:$(params.imageTag)
              docker tag jegornl:$(params.imageTag) harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)
              docker push harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)
      params:
        - name: imageTag
          type: string
          description: Tag for the Docker image
          default: "latest"
