apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextjs-service
spec:
  selector:
    app: {{ .Release.Name }}-nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.servicePort }}
