apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-deploy-pipeline
  namespace: argocd
spec:
  project: {{ .Release.Name }}-project
  source:
    repoURL: "https://github.com/jopdorp/jegor.nl"
    path: charts/jegor-nl
    targetRevision: "production"
    helm:
      releaseName: "jegor-nl"
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jegor-nl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
