apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)  # URL to clone the repository
    - name: branch
      value: $(body.pull_request.base.ref)  # The base branch (target) of the PR
