apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-github-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: github-push-template
      interceptors:
        - ref:
            name: "github"
          params:
            - name: eventTypes
              value:
                - push
            - name: "secretRef"
              value:
                secretName: tekton-webhook-secret
                secretKey: token
        - ref:
            name: cel
          params:
            - name: "filter"  # Correct structure for CEL filter
              value: "body.ref.split('/')[2] == 'main'"
