---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tekton-build-pipeline
spec:
  workspaces:
    - name: source-workspace
  params:
    - name: gitrepositoryurl
      type: string
    - name: branch
      type: string
  tasks:
    - name: pull-code
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: gitrepositoryurl
          value: $(params.gitrepositoryurl)
        - name: branch
          value: $(params.branch)
      taskSpec:      
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        params:
          - name: gitrepositoryurl
            type: string
          - name: branch
            type: string
        steps:
          - name: clone-repo
            image: alpine/git
            script: |
              rm -rf /workspace/source
              git clone "$(params.gitrepositoryurl)" -b "$(params.branch)" /workspace/source
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token
        volumes:
          - name: github-token
            secret:
              secretName: github-secret

    - name: determine-next-image-tag
      runAfter: [pull-code]
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      taskSpec:
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        results:
          - name: new-image-tag
        steps:
          - name: increment-version
            image: bash:latest
            script: |
              #!/usr/bin/env bash
              cd /workspace/source
              current_version=$(grep 'imageTag:' charts/jegor-nl/values.yaml | cut -d' ' -f2)
              version_number=${current_version#v}
              IFS='.' read -r major minor patch <<< "$version_number"
              new_version="v$major.$minor.$((patch+1))"
              echo -n "$new_version" > $(results.new-image-tag.path)
        
    - name: build-docker-image
      runAfter: [determine-next-image-tag]
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: imageTag
          value: $(tasks.determine-next-image-tag.results.new-image-tag)
      taskSpec:
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        params:
          - name: imageTag
            type: string
        steps:
          - name: build
            image: gcr.io/kaniko-project/executor:latest
            args:
              - "--dockerfile=/workspace/source/Dockerfile"
              - "--context=/workspace/source"
              - "--destination=harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)"
            volumeMounts:
              - name: docker-config
                mountPath: /kaniko/.docker
        volumes:
          - name: docker-config
            secret:
              secretName: harbor-credentials
              items:
                - key: .dockerconfigjson
                  path: config.json

    - name: update-argocd-application-and-values
      runAfter: [determine-next-image-tag]
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: imageTag
          value: "$(tasks.determine-next-image-tag.results.new-image-tag)"  # Use result from previous task
      taskSpec:
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        params:
          - name: imageTag
        volumes:
          - name: github-token
            secret:
              secretName: github-secret
        steps:
          - name: update-manifest-and-values
            image: alpine/git
            script: |
              cd /workspace/source

              git config --global user.email "tekton@jopdorp.nl"
              git config --global user.name "Tekton Bot"
              echo "https://bot-user:$(cat /root/github-secret-dir/token)@github.com" > /root/.git-credentials
              git config --global credential.helper store

              sed -i "s/imageTag: .*/imageTag: $(params.imageTag)/" charts/jegor-nl/values.yaml
              sed -i "s/imageTag: .*/imageTag: $(params.imageTag)/" charts/cicd/values.yaml

              git add charts/jegor-nl/values.yaml
              git add charts/cicd/values.yaml
              git commit -m "Automated update to image tag $(params.imageTag) [ci skip]"
              git push origin main
            volumeMounts:
              - name: github-token
                mountPath: /root/github-secret-dir

    - name: upgrade-helm-chart
      runafter: [update-argocd-application-and-values, build-docker-image]
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      taskSpec:
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        volumes:
          - name: kubeconfig-volume
            secret:
              secretName: kubeconfig-secret
        steps:
          - name: upgrade-chart
            volumeMounts:
              - name: kubeconfig-volume
                mountPath: /kubeconfig
            image: alpine/helm:3.11.1
            script: |
              export KUBECONFIG=/kubeconfig/kubeconfig
              cd /workspace/source/charts/cicd
              helm upgrade jegor-nl-cicd . --namespace jegor-nl

    - name: create-github-tag
      runafter: [upgrade-helm-chart]
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: gitrepositoryurl
          value: "$(params.gitrepositoryurl)"
        - name: imageTag
          value: "$(tasks.determine-next-image-tag.results.new-image-tag)"  # Use result from previous task
      taskSpec:
        workspaces:
          - name: source-workspace
            mountPath: /workspace
        params:
          - name: imageTag
            type: string
          - name: gitrepositoryurl
            type: string
        steps:
          - name: create-tag
            image: curlimages/curl:7.78.0
            script: |
              curl -u "bot-user:$(cat /root/.git-credentials)" \
                  -H "Content-Type: application/json" \
                  -X POST $(params.gitrepositoryurl)/git/refs \
                  -d '{"ref": "refs/tags/$(params.imageTag)", "sha": "$(git rev-parse HEAD)"}'
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token
        volumes:
          - name: github-token
            secret:
              secretName: github-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jegornl-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
