apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Release.Name }}-tekton-build-pipeline
spec:
  workspaces:
    - name: source-workspace

  tasks:
    - name: pull-code
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: repo-url  # No 'type' field needed
        - name: branch    # No 'type' field needed
      taskSpec:
        steps:
          - name: clone-repo
            image: alpine/git
            script: |
              git clone $(params.repo-url) -b $(params.branch) /workspace/source
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token

    - name: determine-next-image-tag
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      taskSpec:
        results:
          - name: new-image-tag
        steps:
          - name: increment-version
            image: alpine
            script: |
              cd /workspace/source
              current_version=$(grep 'imageTag:' charts/jegor-nl/values.yaml | cut -d' ' -f2)
              IFS='.' read -r major minor patch <<< "$current_version"
              new_version="$major.$minor.$((patch+1))"
              echo "New version: $new_version"
              echo "$new_version" > /tekton/results/new-image-tag

    - name: build-docker-image
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: imageTag
          value: "$(tasks.determine-next-image-tag.results.new-image-tag)"  # Use result from previous task
      taskSpec:
        steps:
          - name: build
            image: docker:20.10
            script: |
              cd /workspace/source
              docker build . -t jegornl:$(params.imageTag)
              docker tag jegornl:$(params.imageTag) harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)
              docker push harbor.k8s.jegor.nl/jopdorp/jegornl:$(params.imageTag)

    - name: update-argocd-application-and-values
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      taskSpec:
        steps:
          - name: update-manifest-and-values
            image: alpine
            script: |
              cd /workspace/source
              sed -i "s/imageTag: .*/imageTag: \"$(tasks.determine-next-image-tag.results.new-image-tag)\"/" charts/jegor-nl/values.yaml
              git add charts/jegor-nl/values.yaml
              git commit -m "Update to image tag $(tasks.determine-next-image-tag.results.new-image-tag)"
              git push origin master

    - name: upgrade-helm-chart
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      taskSpec:
        steps:
          - name: upgrade-chart
            image: alpine/helm:3.7.0
            script: |
              cd /workspace/source/charts/cicd
              helm upgrade jegor-nl-cicd . --namespace jegor-nl

    - name: create-github-tag
      workspaces:
        - name: source-workspace
          workspace: source-workspace
      params:
        - name: repo-url
          type: string
          default: "https://api.github.com/repos/jopdorp/example"
      taskSpec:
        steps:
          - name: create-tag
            image: curlimages/curl:7.78.0
            script: |
              curl -H "Authorization: token $(cat /root/.git-credentials)" \
                   -H "Content-Type: application/json" \
                   -X POST $(params.repo-url)/git/refs \
                   -d '{"ref": "refs/tags/$(tasks.determine-next-image-tag.results.new-image-tag)", "sha": "$(git rev-parse HEAD)"}'
            volumeMounts:
              - name: github-token
                mountPath: /root/.git-credentials
                subPath: token
