apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-github-listener-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: webhook.tekton.jegor-nl.k8s.jegor.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tekton-webhook-listener
                port:
                  number: 8080  # Ensure this matches the service port
  tls:
    - hosts:
        - webhook.tekton.jegor-nl.k8s.jegor.nl
      secretName: tekton-listener-tls  # TLS secret that will store the certificate
