apiVersion: v1
kind: Service
metadata:
  name: tekton-webhook-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tekton-git-webhook-listener
