---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-github-listener-ingress
  annotations:
    kubernetes.io/ingress.className: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: webhook.tekton.jegor-nl.k8s.jegor.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-tekton-github-listener
                port:
                  number: 8080
  tls:
    - hosts:
        - webhook.tekton.jegor-nl.k8s.jegor.nl
      secretName: tekton-listener-tls
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-github-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: github-push-template
      interceptors:
        - ref:
            name: "github"
          params:
            - name: eventTypes
              value:
                - push
            - name: secretRef
              value:
                secretName: tekton-webhook-secret
                secretKey: token
        - ref:
            name: cel
          params:
            - name: filter
              value: body.ref == 'refs/heads/main'
        - ref:
            name: cel
          params:
            - name: overlays
              value:
                - key: branch
                  expression: "body.ref.split('/').last()"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: branch
      value: $(extensions.branch)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-push-template
spec:
  params:
    - name: gitrepositoryurl
    - name: branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-push-pipelinerun-
      spec:
        params:
          - name: repo-url
            value: $(params.gitrepositoryurl)
          - name: branch
            value: $(params.branch)
        pipelineRef:
          name: {{ .Release.Name }}-tekton-build-pipeline
        workspaces:
          - name: source-workspace
            persistentVolumeClaim:
              claimName: jegornl-pvc
